version: '3.8'

services:
  product:
    build: ./ProductServiceAPI
    container_name: product-service
    ports:
      - "5103:5103"
    networks:
      - ecommerce-net

  order:
    build: ./OderServiceAPI
    container_name: order-service
    ports:
      - "5256:5256"
    networks:
      - ecommerce-net

  user:
    build: ./UserServiceAPI
    container_name: user-service
    ports:
      - "5036:5036"
    networks:
      - ecommerce-net

  api-gateway:
    build: ./Eccommerce
    container_name: api-gateway
    ports:
      - "5251:5251"
    depends_on:
      - product
      - order
      - user
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge