services:
  api-gateway:
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5251:8080"
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build:
      context: ./UserServiceAPI
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5036:8080"

  product-service:
    build:
      context: ./ProductServiceAPI
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5103:8080"

  order-service:
    build:
      context: ./OderServiceAPI
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ApiGateway__BaseUrl=http://api-gateway:8080
    ports:
      - "5256:8080"